source 'https://rubygems.org'
ruby '2.2.3'

gem 'lita'
gem 'lita-slack'
gem 'lita-google-images'
gem 'lita-karma'
gem 'lita-chuck_norris'
gem 'lita-logger'
gem 'lita-whois'
gem 'lita-youtube'
gem 'lita-dice'
gem 'lita-days'
gem 'lita-hackersays'
gem 'lita-custom-meme'
gem 'lita-eightball'
gem 'lita-eval'
gem 'lita-applause'
gem 'moiscot-problem'
gem 'moiscot-coffee', git: 'https://github.com/moi-team/moiScot-coffee.git'
gem 'lita-tuc'

gem 'dotenv'
gem 'puma'
