source 'https://rubygems.org'
ruby '2.2.0'

gem 'lita'
gem 'lita-slack'
gem 'lita-google-images'
gem 'lita-karma'
gem 'lita-chuck_norris'
gem 'lita-logger'
gem 'lita-whois'
gem 'lita-youtube'
gem 'lita-custom-meme'
gem 'moiscot-problem'

gem 'dotenv'
gem 'puma'
